OnlineTextShare/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path('accounts/',include('django.contrib.auth.urls'))
]

posts/urls.py
from django.urls import path
from .views import (PostCreateview,HomePostsListView,
                    PostDetailview,PostUpdateView,PostDeleteView,
                    SignUpCreateView,UserPostListView,PublicPostDetailview,
                    AboutView)
app_name = 'posts'

urlpatterns = [
    path('',HomePostsListView.as_view(),name='home'),
    path('create_post/',PostCreateview.as_view(),name='create_post'),
    path('list_posts/',UserPostListView.as_view(),name='list_posts'),
    path('post_detail/<int:pk>',PostDetailview.as_view(),name='detail_post'),
    path('public_post_detail/<int:pk>',PublicPostDetailview.as_view(),name='public_detail_post'),
    path('update_post/<int:pk>',PostUpdateView.as_view(),name='post_update'),
    path('delete_post/<int:pk>',PostDeleteView.as_view(),name='delete_post'),
    path('signup/',SignUpCreateView.as_view(),name='signup'),
    path('about/',AboutView.as_view(),name='about'),
]

posts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    is_publick = models.BooleanField(default=False)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    
    class Meta:
        ordering = ['-date_posted']

        
    def __str__(self):
        return self.title

posts/views.py
from django.views.generic import CreateView,ListView,DetailView,UpdateView,DeleteView,TemplateView
from .models import Post
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin 

# Create your views here.

# class HomeView(TemplateView):
#     template_name = 'posts/index.html'

#     context_object_name = 'posts_list'
#     def get_queryset(self):
#         return Post.objects.filter(is_publick=True)
    

class PostCreateview(LoginRequiredMixin,CreateView):           # templat = > post_form.html
    model = Post
    fields = ['title','content','is_publick']

    success_url = reverse_lazy('posts:list_posts')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class HomePostsListView(ListView):   #home page           # template = > index.html
    model = Post
    template_name = 'posts/index.html'

    context_object_name = 'posts_list'
    def get_queryset(self):
        return Post.objects.filter(is_publick=True)
    
class UserPostListView(LoginRequiredMixin,ListView):
    model=Post
    template_name = 'posts/post_list.html'
    context_object_name = 'posts_list'
    paginate_by = 6

    def get_queryset(self):
        if self.request.user.is_staff:           # check if superuser is logedin, show all posts
            return Post.objects.all()
        
        return Post.objects.filter(user=self.request.user)         # if regular user,only show the users posts

class PostDetailview(LoginRequiredMixin,DetailView):           # tempalte = > post_detail.html
    model = Post

class PublicPostDetailview(DetailView):           # tempalte = > public_post_detail.html
    model = Post
    template_name = 'posts/public_post_detail.html'


class PostUpdateView(LoginRequiredMixin,UpdateView):           # template = > post_form.html    build befor
    model = Post
    fields = ['title', 'content','is_publick']
    # success_url = reverse_lazy('posts:list_posts') 
    success_url = reverse_lazy('posts:list_posts')
    

class PostDeleteView(LoginRequiredMixin,DeleteView):           # template = > post_confirm_delete.html
    model = Post
    # success_url = reverse_lazy('posts:list_posts')
    success_url = reverse_lazy('posts:home')

class SignUpCreateView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')

    template_name = 'registration/signup.html'


class AboutView(TemplateView):
    template_name = 'posts/about.html'

posts/templates/posts/about.html
{% extends "posts/base.html" %}
{% load static %}
{% block content %}
   
{% comment %}       
            <section class="banner_main_home">
               <div class="container">
                  <div class="row d_flex">
                     <div class=" col-xl-8 col-lg-8 col-md-8 col-12-9">
                        <div class="text-bg">
                           <h1>Online<br> <span class="white1">Text Share</span></h1>
                           <p>Hi,in Online Text Share,you can share your text and links to 
                              access it anywhere,on your phone or desktop.you can easily share it for yourself. </p>
                           <a href=' {% url "posts:signup" %} '>Start Heare</a>
                        </div>
                     </div>
                  </div>
               </div>
            </section>
         </div> {% endcomment %}
      </header>
      <!-- end banner -->
      <!-- blog_main -->
      <div class="blog_main">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     <div class="about">
                        <h2>About me</h2>
                        <span>Hello! I'm Seyed Mojtaba Esmaili, a junior Python Django backend developer
                            with a passion for learning and growing in the world of web development. I 
                            enjoy building dynamic and efficient web applications and am excited to deepen
                             my expertise in Python and the Django framework.
                           On my GitHub, you'll find a collection of projects that showcase my journey 
                           as a developer. I’m eager to tackle
                             new challenges and continuously improve my skills through hands-on experience and 
                             collaboration.
                            I believe
                             in the importance of community and am always open to connecting with fellow developers
                              and learning from their experiences.                          
                           Let’s connect and explore the exciting possibilities in the world of development together!
                        </span>
                     </div>   
                  </div>
               </div>
            </div>
            <!-- fist section -->

            <!-- ############ -->
            <div class='card-container'>
               {% for post in posts_list %}
                  
                     <div class='card'>
                        <div class='card-content'>
                           {% comment %} <article> {% endcomment %}
                              <h3>{{post.title}}</h3>
                              <h4>Writer : <b><i>{{post.user.username}}</i></b></h4>
                              <h4>Time Posted : {{post.date_posted}}</h4>
                              <p>{{post.content|truncatewords:25}}</p>
                              <a href='/public_post_detail/{{post.id}}' class='post-btn'>Read More</a>
                           {% comment %} </article> {% endcomment %}
                        </div>
                     </div>
                  
               {% endfor %}
            </div>
            
    <!-- end fist section -->
         </div>
      </div>
      <!-- end blog_main -->

      {% endblock content %}

posts/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Online Text Share</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'posts/css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'posts/css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'posts/css/responsive.css' %}">
      <!-- fevicon -->
      {% comment %} <link rel="icon" href="{% static 'posts/images/fevicon.png' %}" type="image/gif" /> {% endcomment %}
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'posts/css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout">
    <!-- header -->
    <header>
        <!-- header inner -->
        <div  {% if request.path == "/" or request.path == "/accounts/logout/" %}
                  class="head_top"
               {% else %}
                  class="head_top1"
               {% endif %}>
           <div class="header">
              <div class="container-fluid">
                 <div class="row">
                    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                       <div class="full">
                          <div class="center-desk">
                             <div class="logo">
                                <a href='{% url "posts:home" %}'><img src="{% static 'posts/images/logo.png' %}" alt="#" /></a>
                             </div>
                          </div>
                       </div>
                    </div>
                    <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                       <nav class="navigation navbar navbar-expand-md navbar-dark ">
                          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                          </button>
                          <div class="collapse navbar-collapse" id="navbarsExample04">
                             <ul class="navbar-nav mr-auto">
                                <li class="nav-item">
                                   <a class="nav-link" href='{% url "posts:home" %}'> Home  </a>
                                </li>
                                <li class="nav-item">
                                   <a class="nav-link" href=' {% url "posts:about" %} '>About</a>
                                </li>
                                <li class="nav-item">
                                   <a class="nav-link" href=' {% url "posts:create_post" %} '>Create</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href=' {% url "posts:list_posts" %} '>List</a>
                                 </li>
                                {% if user.is_authenticated %}
                                   
                                   <li class="nav-item">
                                       <form method="post" action="{% url 'logout' %}">
                                          {% csrf_token %}
                                          <a class="nav-link" href=' {% url "logout" %} '><button type="submit" >logout</button></a>
                                       {% comment %} <a class="nav-link" href=' {% url "logout" %} '>Logout</a> {% endcomment %}
                                    </form>
                                    </li>
                                {% else %}
                                    <li class="nav-item">
                                       <a class="nav-link" href=' {% url "login" %} '>LogIn</a>
                                    </li>
                                    <li class="nav-item">
                                       <a class="nav-link" href=' {% url "posts:signup" %} '>SignIn</a>
                                    </li>
                                   {% comment %} <a href=' {% url "login" %} '>LogIn</a>
                                   <a href=' {% url "posts:signup" %} '>SignIn</a> {% endcomment %}
                                {% endif %}
                             </ul>
                          </div>
                       </nav>
                    </div>
                 </div>
              </div>
           </div>
           <!-- end header inner -->
           <!-- end header -->
           <!-- banner -->
   

{% block content %}

{% endblock content %}
<!--  footer -->
<footer>
    <div class="footer">
       <div class="container">
          <div class="row">
             <div class="col-md-12 ">
                <div class="cont">
                   <h3> <strong class="multi"> Online Text Share</strong><br>
                      Seyed Mojtaba Esmaili
                   </h3>
                </div>
             </div>
             <div class="col-md-12">
                <ul class="social_icon">
                   <li><a href="https://github.com/SMojtabaE" target=”_blank”><i class="fa fa-github" aria-hidden="true"></i></a></li>
                   <li><a href="https://www.linkedin.com/in/seyed-mojtaba-esmaili/" target=”_blank”><i class="fa fa-linkedin" aria-hidden="true"></i></i></a></li>
                </ul>
             </div>

          </div>
       </div>
       <div class="copyright">
          <div class="container">
             <div class="row">
                <div class="col-md-12">
                   <p>Seyed Mojtaba Esmaili</p>
                </div>
             </div>
          </div>
       </div>
    </div>
 </footer>
 <!-- end footer -->
 <!-- Javascript files-->
 <script src="{% static 'posts/js/jquery.min.js' %}"></script>
 <script src="{% static 'posts/js/popper.min.js' %}"></script>
 <script src="{% static 'posts/js/bootstrap.bundle.min.js' %}"></script>
 <script src="{% static 'posts/js/jquery-3.0.0.min.js' %}"></script>
 
 <!-- sidebar -->
 <script src="{% static 'posts/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
 <script src="{% static 'posts/js/custom.js' %}"></script>
 <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
</body>
</html>




{% comment %} {% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Posts</title>
    <link rel="stylesheet" href="{% static 'posts/style.css' %}">
</head>
<body>
<div class='navbar'>
    <a href=' {% url "posts:home" %} '>Home Page</a>
    {% if user.is_authenticated %}
        <a href=' {% url "logout" %} '>Logout from {{user.get_username}}</a>
    {% else %}
        <a href=' {% url "login" %} '>LogIn</a>
        <a href=' {% url "posts:signup" %} '>SignIn</a>
    {% endif %}
</div>


{% block content %}


{% endblock content %}

</body>
</html> {% endcomment %}

posts/templates/posts/index.html
{% extends "posts/base.html" %}
{% load static %}
{% block content %}
   
      
            <section class="banner_main_home">
               <div class="container">
                  <div class="row d_flex">
                     <div class=" col-xl-8 col-lg-8 col-md-8 col-12-9">
                        <div class="text-bg">
                           <h1>Online<br> <span class="white1">Text Share</span></h1>
                           <p>Hi,in Online Text Share,you can share your text and links to 
                              access it anywhere,on your phone or desktop.you can easily share it for yourself. </p>
                           <a href=' {% url "posts:signup" %} '>Start Heare</a>
                        </div>
                     </div>
                  </div>
               </div>
            </section>
         </div>
      </header>
      <!-- end banner -->
      <!-- blog_main -->
      <div class="blog_main">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     <h2>Public Posts</h2>
                     <span>In this part,you can see the public post that people uploaded</span>
                  </div>
               </div>
            </div>
            <!-- fist section -->

            <!-- ############ -->
            <div class='card-container'>
               {% for post in posts_list %}
                  
                     <div class='card'>
                        <div class='card-content'>
                           {% comment %} <article> {% endcomment %}
                              <h3>{{post.title}}</h3>
                              <h4>Writer : <b><i>{{post.user.username}}</i></b></h4>
                              <h4>Time Posted : {{post.date_posted}}</h4>
                              <p>{{post.content|truncatewords:25}}</p>
                              <a href='/public_post_detail/{{post.id}}' class='post-btn'>Read More</a>
                           {% comment %} </article> {% endcomment %}
                        </div>
                     </div>
                  
               {% endfor %}
            </div>
            
    <!-- end fist section -->
         </div>
      </div>
      <!-- end blog_main -->

      {% endblock content %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/base.html" %}


{% block content %}
</header>
    {% comment %} <div class='post-delete-main'>
        <div class='post'>
            <h3>Are you sure you want to Delete this Post?</h3>
            <p><b>Title</b> : {{post.title}}</p>

            <form method='POST'>
                {% csrf_token %}
                <input class='detailbtn deletebtn' type='submit' value='delete'>
            </form>
        </div>
    </div> {% endcomment %}

    {% comment %} <section class="banner_main">
        <div class="container">
           <div class="row d_flex">
              <div class=" col-xl-8 col-lg-8 col-md-8 col-12-9">
                 <div class="text-bg">
                    <h1>Online<br> <span class="white1">Text Share</span></h1>
                    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,</p>
                    <a href=' {% url "posts:signup" %} '>Start Heare</a>
                 </div>
              </div>
           </div>
        </div>
     </section>
    </div> 
    </header> {% endcomment %}
{% if form.user != user %}      {% comment %} checks if the user is the same one that made the post {% endcomment %}
    
        <p class="error"> You dont have permission for this page</p>
{% else %} 

<div class="blog_main">
    <div class="container">
        <div class='card-container'>
                  <div class='card-detail'>
                     <div class='card-content'>
                        <form method='POST'>
                            {% csrf_token %}
                           <h3>Are you sure you want to delete this post?</h3>
                           <hr style="background:#046c58;">
                           <h4>Title : <b><i>{{post.title}}</i></b></h4>  
                        
                            <div class='post-btns'>
                                <input class='post-btn-delete' type='submit' value='delete'>
                                
                            </div>
                        </form>
                     </div>
                  </div>
         </div>
    </div>
</div>
{% endif %} 




{% endblock content %}

posts/templates/posts/post_detail.html
{% extends "posts/base.html" %}


{% block content %}
{% comment %} <section class="banner_main">
    <div class="container">
       <div class="row d_flex">
          <div class=" col-xl-8 col-lg-8 col-md-8 col-12-9">
             <div class="text-bg">
                <h1>Online<br> <span class="white1">Text Share</span></h1>
                <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,</p>
                <a href=' {% url "posts:signup" %} '>Start Heare</a>
             </div>
          </div>
       </div>
    </div>
 </section>
</div>  {% endcomment %}
</header>
{% comment %} <div class="blog_main">
    <div class="container">
       <div class="row">
          <div class="col-md-12">
             <div class="titlepage">
                <h2>Public Posts</h2>
                <span>In this part,you can see the public post that people uploaded</span>
             </div>
          </div>
       </div> {% endcomment %}
        {% comment %} <main class='post-detail-main'>
            <div class='post'>
                <article>
                    <h2>Title : <b><i>{{post.title}}</i></b></h2>
                    <hr>
                    <h3>Writer : <b><i>{{post.user.username}}</i></b></h3>
                    <hr>
                    <h4>Time Posted : {{post.date_posted}}</h4>
                    <hr>
                    <p>{{post.content}}</p>
                    </article>
                    <div class='post-btns'>
                        <a  href='/update_post/{{post.id}}'><button class='detailbtn updatebtn'>Update</button></a>
                        <a  href='/delete_post/{{post.id}}'><button class='detailbtn deletebtn'>Delete</button></a>
                    </div>
            </div>
        </main> {% endcomment %}
        {% if post.user != user %}      {% comment %} checks if the user is the same one that made the post {% endcomment %}
    
            <p class="error"> You dont have permission for this page</p>
         {% else %} 
            <div class='card-container'>
                     <div class='card-detail'>
                        <div class='card-content'>
                           <article>
                              <h3>{{post.title}}</h3>
                              <hr style="background:#046c58;">
                              <h4>Writer : <b><i>{{post.user.username}}</i></b></h4>
                              <hr style="background:#046c58;">
                              <h4>Time Posted : {{post.date_posted}}</h4>
                              <hr style="background:#046c58;">
                              <p>{{post.content}}</p>
                              
                              {% comment %} <a href='/post_detail/{{post.id}}' class='post-btn'>Read More</a> {% endcomment %}
                           </article>
                        <div class='post-btns'>
                           <a  href='/update_post/{{post.id}}'><button class='post-btn'>Update</button></a>
                           <a  href='/delete_post/{{post.id}}'><button class='post-btn-delete'>Delete</button></a>
                        </div>
                     </div>
                  </div>
            </div>
         {% endif %}
    </div>
</div>
{% endblock content %}

posts/templates/posts/post_form.html
{% extends "posts/base.html" %}
{% block content %}
{% comment %} <div class='form-main'>
    <div class='form-container'>
        <h1>Create New Post</h1>
        <form class='form' method='POST'>
            {% csrf_token %}
            {{form.as_p}}
            <div class='post-btns'>
                <input class='detailbtn' type='submit' value='Post'>
            </div>
        </form>
    </div>
</div> {% endcomment %}
{% comment %} <section class="banner_main">
    <div class="container">
       <div class="row d_flex">
          <div class=" col-xl-8 col-lg-8 col-md-8 col-12-9">
             <div class="text-bg">
                <h1>Online<br> <span class="white1">Text Share</span></h1>
                <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,</p>
                <a href=' {% url "posts:signup" %} '>Start Heare</a>
             </div>
          </div>
       </div>
    </div>
 </section>
</div>  {% endcomment %}
</header>
    <div id="contact" class="contact">   
        <div class="container">
            <div class="row">
                <div class="col-md-12 ">
                    <form class="main_form " method='POST'>
                        {% csrf_token %}

                        <div class="row">
                            <div class="col-md-12 ">
                                <input class="form_contril" placeholder="Title " type="text" name="title" value="{% if form.title.value %} {{ form.title.value }} {% else %}{% endif %}">
                                
                                {% for err in form.title.errors %}
                                    <small class='text-danger'>{{err}}</small>
                                {% endfor %}
                                
                            </div>
                            <div class="col-md-12">
                                <textarea class="textarea" placeholder="Content" type="text" name="content">{% if form.content.value %}{{ form.content.value }}{% endif %}</textarea>
                                
                                {% for err in form.content.errors %}
                                    <small class='text-danger'>{{err}}</small>
                                {% endfor %}
                            </div>
                            <div class='form-checkbox'>
                                <label for="is_publick" class='form-checkbox-label'> is publick?</label>
                                <input type="checkbox" id="is_publick" name="is_publick" {% if form.is_publick.value %}checked{% endif %} />
                                
                              </div>
                            <div class="col-sm-12">
                                <button class="send_btn">Post</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% comment %} </div> {% endcomment %}

{% endblock content %}

posts/templates/posts/post_list.html
{% extends "posts/base.html" %}
{% load static %}

{% block content %}
{% comment %} <h1>Lost Of Post</h1>
<main class='post-list-main'>
    {% for post in posts_list %}
        <div class='post'>
            <article>
                <h2>Title : <b><i>{{post.title}}</i></b></h2>
                <h3>Writer : <b><i>{{post.user.username}}</i></b></h3>
                <h4>Time Posted : {{post.date_posted}}</h4>
                <p>{{post.content|truncatewords:25}}</p>
                <a href='/post_detail/{{post.id}}'>More</a>
                </article>
        </div>      
    {% endfor %}
</main> {% endcomment %}
   
{% comment %}       
            <section class="banner_main">
               <div class="container">
                  <div class="row d_flex">
                     <div class=" col-xl-8 col-lg-8 col-md-8 col-12-9">
                        <div class="text-bg">
                           <h1>Online<br> <span class="white1">Text Share</span></h1>
                           <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,</p>
                           <a href=' {% url "posts:signup" %} '>Start Heare</a>
                        </div>
                     </div>
                     {% comment %} <div class="col-xl-4 col-lg-4 col-md-4 col-12-3">
                        <div class="text-img">
                           <figure><img src="{% static 'posts/images/box_img.png' %}" alt="#"/></figure>
                        </div>
                     </div> 
                  </div>
               </div>
            </section>
         </div>{% endcomment %}
      </header> 
      <!-- end banner -->
      <!-- blog_main -->

      
      <div class="blog_main">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     
                     <h2>User Posts</h2>
                     <span>In this part,you can see the post that you uploaded</span>
                  </div>
               </div>
            </div>
            <!-- fist section -->

            <!-- ############ -->
            <div class='card-container'>
               {% for post in posts_list %}
                  
                     <div class='card'>
                        <div class='card-content'>
                           {% comment %} <article> {% endcomment %}
                              <h3>{{post.title}}</h3>
                              <h4>Writer : <b><i>{{post.user.username}}</i></b></h4>
                              <h4>Time Posted : {{post.date_posted}}</h4>
                              <p>{{post.content|truncatewords:25}}</p>
                              <a href='/post_detail/{{post.id}}' class='post-btn'>Read More</a>
                           {% comment %} </article> {% endcomment %}
                        </div>
                     </div>
                  
               {% endfor %}
            </div>
            
    <!-- end fist section -->
    <div class="pagination">
         
      <div class="pagination">
         
         {% if page_obj.has_previous %}
             <a href="?page=1">&laquo; first</a>
             <a href="?page={{ page_obj.previous_page_number }}">previous</a>
         {% endif %}

      
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  
</div>
         </div>


         
      </div>
      <!-- end blog_main -->
      
{% endblock content %}